name: Test workflow
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

jobs:
  build:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - name: github repository
        run: echo "${{ github.repository }}"
      - name: checkout
        uses: actions/checkout@v3
      - name: Create HTML test report artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-artifact
          path: testfile.txt
      - uses: octokit/request-action@v2.x
        id: get_artifacts
        with:
          route: GET /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: 'echo "Artifacts: ${{ steps.get_artifacts.outputs.data }}"'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - id: get_version
        run: |
          echo "publish_version=`./gradlew -q -Prelease.quiet cV`" >> $GITHUB_OUTPUT
      - name: Place report URL in the summary
        run: |
          echo "Publish version is: <${{ steps.get_version.outputs.publish_version }}>" >> $GITHUB_STEP_SUMMARY
      - name: test multiline env
        run: |
          MULTI_LINES_TEXT="this is line one \n
                            this is line two \n
                            this is line three \n"
          echo "MULTI_LINES_TEXT_ENV_VAR=$MULTI_LINES_TEXT" >> $GITHUB_ENV
