name: Test workflow
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

jobs:
  build:
    name: Test job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 10, 12, 14 ]
    steps:
      - name: Save matrix version in step summary
        run: |
          echo 'Matrix version: ${{ matrix.version }}' >> $GITHUB_STEP_SUMMARY
      - id: create_artifact
        run: echo "${{ matrix.version }}" > version.txt
      - id: upload_artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-artifact-${{ matrix.version }}
          path: version.txt

  process_artifacts:
    runs-on: ubuntu-latest
    steps:
      - id: download_artifacts
        uses: actions/download-artifact@v3
        with:
          name: test-artifact-*
      - name: list artifacts
        run: ls -la
