name: Test workflow
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

jobs:
  build:
    name: Test job
    runs-on: ubuntu-latest
    outputs:
      output1: {{ steps.generate_output.outputs.matrix_version }}
    strategy:
      matrix:
        version: [10, 12, 14]
    steps:
      - name: Save matrix version in step summary
        run: |
          echo 'Matrix version: ${{ matrix.version }}' >> $GITHUB_STEP_SUMMARY
      - id: generate_output
        run: |
          echo 'matrix_version=${{ matrix.version }}' >> $GITHUB_OUTPUTS

  postbuild:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Print job output
        run: |
          echo "${{ needs.build.outputs.output1 }}"
