name: Test workflow
on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Create HTML test report artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-artifact
          path: testfile.txt
      - uses: octokit/request-action@v2.x
        id: get_artifacts
        with:
          route: GET /repos/{owner}/{repo}/actions/runs/{run_id}/artifacts
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          run_id: ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo Artifacts: ${{ steps.get_artifacts.outputs.data }}"
