name: Test workflow
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

jobs:
  event_file:
    name: "Event File"
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Event File
          path: ${{ github.event_path }}

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64
          distribution: 'temurin'
      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      - name: Create JUnit HTML test report artifact
        # don't run this step only if workflow was cancelled
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: junit-html-test-report
          path: lib/build/reports/tests/test
      - name: Create JUnit XML test report artifact
        # don't run this step only if workflow was cancelled
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: junit-xml-test-report
          path: lib/build/test-results/test
